### ISSUE TITLE
How to nested subresource?

### ISSUE THREAD

**Issue by kethan** [artzstudio/meanify#5]
Can you please help me more than one sub-resource ie nested?

**Comment by artzstudio** [comment]
Hey there, this is currently not supported and not a current priority.  Do
you think you can simplify your scheme structure for now to avoid the
nesting?

**Comment by kethan** [comment]
No just for understanding purpose i would like to implement it..can you please give me some hint or example how to use it?

**Comment by kethan** [comment]
Anyway thank you i have implemented it..

rec = function(schema) {
    var fields = [];
    var paths = Object.keys(schema.paths);
    for (i in paths) {
        var path = paths[i];
        var nestedSchema = schema.paths[path].schema;
        if (nestedSchema) {
            var nestedFields = rec(nestedSchema);
            for (i in nestedFields) {
                fields.push(path + '.0.' + nestedFields[i]);
            }
        } else if (schema.paths[path].caster) {
            fields.push(path + '.0');
        } else {
            fields.push(path);
        }
    }
    var virtuals = Object.keys(schema.virtuals);
    fields = _.union(fields, virtuals);
    return _.without(fields, '_id', '__v');
};

Thanks to restberry.
